### ISSUE TITLE
Node 20 compatibility

### ISSUE THREAD

**Issue by holtwick** [daveagill/verify-paddle-webhook#11]
Looks like some stuff has been deprecated in node. This error shows up:

```
{
  "code": "ERR_OSSL_UNSUPPORTED",
  "library": "DECODER routines",
  "reason": "unsupported",
}
```

Not very important, but maybe you've a quick idea how to solve it? Webcrypto?

**Comment by holtwick** [comment]
Sorry, my fault. Error was on my end.

**Comment by daveagill** [comment]
No worries :)

Sounds like you may be able to switch it back to the old OpenSSL provider if you need to: https://www.code4copy.com/post/err_ossl_evp_unsupported-on-nodejs-17/

**Comment by holtwick** [comment]
The cause was more trivial: I had leading white spaces in each line of the public key 🤦‍♂️

I also tested the `--openssl-legacy-provider` option, but it also worked without it, in node 18 at least.
