### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by ahmedmgh67** [daveagill/verify-paddle-webhook#2]
Thanks for making this package, it has made our life much easier, if there is anything we can contribute with please tell me.
Thanks again

**Comment by daveagill** [comment]
Ahmed, I am delighted to hear it has been helpful to you.

If you don't mind me asking:
* How do you use it? (e.g. In an express.js app?)
* How did you discover this package?

Pull Requests are always welcome if there is anything you think you can improve in the readme, code, tests, or anything else for that matter!

**Comment by ahmedmgh67** [comment]
Hi David, 
Yes exactly we use it as an authentication middleware on the webhook routes
We discovered it in the [ paddle webhook documentation ](https://developer.paddle.com/webhook-reference/verifying-webhooks)
If we find any chance of improvement be sure that we'll submit a pull request

**Comment by daveagill** [comment]
Very interesting!
I had no idea it had been added to Paddle's documentation until now!

**Comment by simonmulser** [comment]
Also thanks from my side! Don't understand why they don't provide something like this.

I found it also on their public doc and I'm using it inside a Netlify function like this:

```
const { verifyPaddleWebhook } = require("verify-paddle-webhook");
const PADDLE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
INSERT YOURS
-----END PUBLIC KEY-----`;
const { parse } = require("qs");

exports.handler = async function (event, context) {
    const body = await parse(event.body);

    if (!verifyPaddleWebhook(PADDLE_PUBLIC_KEY, body)) {
        console.log(`Could not validate signature. Returning.`);
        return {
            statusCode: 200,
        };
    }

    return {
        statusCode: 200,
    };
};
```

**Comment by daveagill** [comment]
Thanks Simon.

I may nab your Netlify example for the readme ;-)
