### ISSUE TITLE
can not verify with null value

### ISSUE THREAD

**Issue by mahbubhasanhira** [daveagill/verify-paddle-webhook#6]
When my webhook post in my adonis js app with ip and coupon value null, that time validator can not verify my webhook. Why paddle send null ip and coupon? and why validator can't validate webhook.

**Comment by daveagill** [comment]
Hi Mahbub,

I am not sure why Paddle is sending you nulls, or whether it is correct or incorrect for them to do so.

I have an idea you could try.

Try changing line 25: https://github.com/daveagill/verify-paddle-webhook/blob/master/index.js#L25
To return the null as a string:

`sorted[k] = v == null ? 'null' : v.toString();`

You could achieve this easily by copy/paste the function into your codebase and installing the needed dependency: `npm install php-serialize`

Compared with the current sample code suggested by Paddle this is the only difference I can really think of in regards to the null handling: https://developer.paddle.com/webhook-reference/ZG9jOjI1MzUzOTg2-verifying-webhooks

If you let me know if this fixes the issue I'll be happy to push a fix through to npm 👍

If it does not fix the issue then it is most likely an issue on Paddle's side and you could raise a support ticket with them. You could also try out their sample code that I linked and if that **does** work then there is definitely a bug here and I would be most interested to know that.

**Comment by mahbubhasanhira** [comment]
Badly this code also not working. I think this is Paddle's problem. Why did they send me the null property which I don't need. When I manually call a webhook with all field from paddle dashboard then there is no issue but when send data with null value it again could not verify the hook.

**Comment by daveagill** [comment]
I recommend you raise a support ticket with Paddle in that case.
In my experience they have been quite good at responding.

I'll be very interested to learn what the outcome is 🙂

**Comment by daveagill** [comment]
Hi @mahbubhasanhira , do you have any update on this or what you did to resolve it?

**Comment by mahbubhasanhira** [comment]
Hi @daveagill, sorry for the late reply. Actually, I solve that issue by communicating with the paddle team. Now everything is fine. And your Plugin is blessed for us.
